### PR TITLE
Support for Remote JS and Remote CSS for the CustomCSS and CustomJS settings

### PR DESCRIPTION
**Pull request by acpmasquerade**
for the support of Netlify Identity and similar features

### CODE REVIEW

**Comment by wojciehm** [comment]
I guess this will never go live. This project is dead.

**Comment by acpmasquerade** [comment]
> I guess this will never go live. This project is dead.

Let's maintain in the other branch then. I will accept pull requests.

**Comment by nodejh** [comment]
Hi @acpmasquerade, thanks for your PR, and I'm sorry that I haven't maintained this project for a long time. I will accept PRs as soon as possible.

**Comment by paulrberg** [comment]
Any updates @nodejh? Love this theme but it needs a bit of polish!

**Comment by nodejh** [comment]
Hi all, thank you very much! I am so sorry that fix this problem so late. Now I have merged this PR :heart:

**Pull request merged**
